### ISSUE TITLE
0.8.0 only works with Merlin's master branch?

### ISSUE THREAD

**Issue by smondet** [314eter/atom-ocaml-merlin#11]
I had a bunch of "Invalid argument" errors after updating to 0.8.0.

Then I pinned `merlin` to its master branch; and now `atom-ocaml-merlin` works again.

Did I get something wrong?
If not, this is worth mentioning in the README?

**Comment by 314eter** [comment]
Version 0.8.0 was meant to work with both master and release. Previously, master was not supported, but it's needed for ocaml 4.03.

It's fixed in 0.8.1.
