### ISSUE TITLE
Wrong display of "Show Type"

### ISSUE THREAD

**Issue by smondet** [314eter/atom-ocaml-merlin#12]
It is right now (0.8.0) all "in-line" which is not readable for long types:

![example](https://www.dropbox.com/s/0nrznvv3ktvytb0/Screenshot%202016-05-26%2011.38.17.png?raw=1)

**Comment by 314eter** [comment]
I agree that's not very useful, but is there a better alternative? It's possible to insert newlines, but then it probably won't fit on your screen vertically.

In my opinion, this feature is meant for fast checking of small types, not for big module signatures.

Suggestions and PR's to enhance the type bubbles are very welcome, I don't like it either, but I'm not a graphical designer :grin:

**Comment by neojski** [comment]
In vim and emacs if the type is long a new split is open with the type.

**Comment by 314eter** [comment]
Types are now displayed with correct newlines and indentation. I created #19 for @neojski's suggestion.
