### ISSUE TITLE
Does not work with no error messages

### ISSUE THREAD

**Issue by neojski** [314eter/atom-ocaml-merlin#18]
I wanted to give it a try but it does not seem to work and shows no error messages. How can I help you debug it?

merlin does work for the same directory using vim.

**Comment by neojski** [comment]
Actually, it is showing errors, I just didn't know how to get them. I had to point `Merlin Path` to `/home/neo/repos/merlin/ocamlmerlin`.

With this it fails with:

```
Merlin exited with code null
/home/neo/.atom/packages/ocaml-merlin/lib/merlin.coffee:40 Merlin process started, pid = 25526
Merlin process started, pid = 25526
```

I'm not yet sure why.

**Comment by neojski** [comment]
It seems that merlin gets unhappy about the query at the beginning:
`["protocol", "version", 2]`
It replies with:
`["failure","invalid arguments"]`

It looks to me that I'm using some incompatible merlin version.

I just updated merlin from opam to version `The Merlin toolkit version 2.3.1, for Ocaml 4.02.3` and it still does not work.

I tried merlin 2.0.0 and some in between but they still do not work.

**Comment by 314eter** [comment]
It works with all versions of Merlin here. The query `["protocol", "version", 2]` is needed to distinguish between older versions (2.3.1 and before) that return the failure message, and newer versions (master branch) that use the new protocol. If Merlin returns the failure message, the protocol is set to 1, and the error should be ignored.

Which versions of atom and ocaml-merlin are you using?

**Comment by neojski** [comment]
I don't actually know what happened but I tried it again today to give you more details and it works!

Maybe I updated something whilst playing with nuclide.
