### ISSUE TITLE
Interested in Reason support?

### ISSUE THREAD

**Issue by chenglou** [314eter/atom-ocaml-merlin#22]
Hey @314eter, I was wondering if you've heard of https://github.com/facebook/reason. Would you be interested in augmenting the ocaml support with the reason one? It'll only take a few lines of changes (merlin already has first-class reason support).

**Comment by jordwalke** [comment]
There's a lot of people looking for a lightweight way to use Reason in Atom. Could this plugin be that solution?

**Comment by 314eter** [comment]
It can be, but I'm not using Reason myself, so I forgot to take a look at it. I'll try to do it later, but PR's are welcome.

**Comment by 314eter** [comment]
I added reason support. But it only works if there is a language package for reason, which is included in nuclide, and nuclide already provides merlin support.

I think it would be nice to have reason support in atom without installing nuclide (and disabling everything you don't need). But that requires a separate `language-reason` package.

@chenglou Is there a reason why `nuclide-language-reason` has to be a nuclide subpackage?

**Comment by chenglou** [comment]
No; I'll keep this in mind and ping you when I pull language-reason out. Thanks!

**Comment by chenglou** [comment]
@314eter ok, I've published https://atom.io/packages/language-reason. This is a copy of the one in nuclide; I'll go remove the nuclide one in the future so that the language-reason repo becomes the source of truth.

**Comment by 314eter** [comment]
I created the [reason-refmt](https://atom.io/packages/reason-refmt) package to make it complete.
