### ISSUE TITLE
Merlin+Atom crashes on Windows 10

### ISSUE THREAD

**Issue by mrakgr** [314eter/atom-ocaml-merlin#25]
First time using Ocaml here, but I've verified that it running correctly in the Cygwin terminal. Here are the steps I took to install it:

1) Got the graphical 64-bit 4.02.3 installer [from here.](https://fdopen.github.io/opam-repository-mingw/installation/) The installation went smoothly.
2)
```
opam install merlin
opam user-setup install
```
The second command gave me a bunch of file not found errors towards the end.
3)
```
E:\Downloads>apm install ocaml-merlin
Installing ocaml-merlin to C:\Users\Marko\.atom\packages done

E:\Downloads>apm install language-ocaml
Installing language-ocaml to C:\Users\Marko\.atom\packages done

E:\Downloads>apm install ocaml-indent
Installing ocaml-indent to C:\Users\Marko\.atom\packages done

E:\Downloads>apm install linter
Installing linter to C:\Users\Marko\.atom\packages done
```
This went smoothly.
4) In Atom I made a new `ocaml-test.ml` file and when I saved it this error pops up.
```
Error: write EPIPE
at exports._errnoException (util.js:1026:11)
at Socket._writeGeneric (net.js:706:26)
at Socket._write (net.js:725:8)
at doWrite (_stream_writable.js:307:12)
at writeOrBuffer (_stream_writable.js:293:5)
at Socket.Writable.write (_stream_writable.js:220:11)
at Socket.write (net.js:651:40)
at Interface._writeToOutput (readline.js:241:17)
at Interface.prompt (readline.js:206:10)
at Interface.question (readline.js:219:12)
at file:///C:/Users/Marko/.atom/packages/ocaml-merlin/lib/merlin.coffee:40:20
at file:///C:/Users/Marko/.atom/packages/ocaml-merlin/lib/merlin.coffee:38:11
```
I suppose there are other plugins I could try, but browsing the Ocaml news, I saw that Merlin was made a headline project so I decided to try it first. I'd like to get it going if possible.

Note: Referenced from [here](https://github.com/ocaml/merlin/issues/616) as per suggestion.

**Comment by 314eter** [comment]
Does ocamlmerlin work from the command line? Is it in your PATH?

**Comment by mrakgr** [comment]
It was not. As soon as I added it - it was in `C:\OCaml64\home\Marko\.opam\4.02.3+mingw64c\bin` for me, it started working. Thanks. Maybe this should be noted in the instructions somewhere.

I should have checked it yesterday instead of opening this issue, but I could not really use the keyboard.

Also while the type errors show up now, I can't figure out how to get the type of a variable. Unlike with Haskell plugin and VS for F#, hovering above them does not work, and there is no option for it with a right click.

**Comment by 314eter** [comment]
Currently, the only way of getting type information is with the command `ocaml-merlin:show-type` in the command palette (`ctrl+shift+p`), to which you can assign your own keyboard shortcut in your keymap.

**Comment by mattiasdrp** [comment]
I have the same error but I installed atom from Windows and merlin from bash. When I open bash and type 
`which ocamlmerlin` it gives me the path `~/.opam/4.04.0/bin/ocamlmerlin` and when I echo `$PATH` the directory `.opam/4.04.0/bin` is listed. Do you have an idea of what the problem may be?

**Comment by agluszak** [comment]
I have the same problem as @mattiasroux  (Atom on Windows, merlin on bash), but I use a proxy file
`@echo off
bash.exe -l -c "ocamlmerlin %*"`
