### ISSUE TITLE
Feature request: syntax highlighting for type hint

### ISSUE THREAD

**Issue by chenglou** [314eter/atom-ocaml-merlin#33]
@314eter I've finally started trying this plugin for Reason; it works well! Thanks.

**Comment by 314eter** [comment]
Syntax highlighting would be nice. I think the only way to do it is by using a mini TextEditor, but I'll have to look into that.
I never liked the type bubbles anyway, they should be revamped entirely, but I don't know how. :slightly_frowning_face:

**Comment by chenglou** [comment]
Fwiw, I think this is now Nuclide's type hint (which works with Reason) works: https://github.com/facebook/nuclide/tree/master/pkg/nuclide-type-hint/lib

**Comment by 314eter** [comment]
I tried it, and I think it looks surprisingly good.
