### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by eldh** [314eter/atom-ocaml-merlin#37]
I get this error on startup. I just got started with ocaml and Reason so not really sure if I messed something up on my end, but thought I'd report anyway.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [ocaml-merlin](https://github.com/314eter/atom-ocaml-merlin) package 0.14.4

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at /packages/ocaml-merlin/lib/merlin.coffee:43:24
    at Interface._onLine (readline.js:230:5)
    at Interface.<anonymous> (readline.js:365:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:364:11)
    at Socket.ondata (readline.js:100:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
busy-signal 1.4.1 
color-picker 2.2.5 
emmet 2.4.3 
hyper-black-syntax 0.1.0 
hyper-black-ui 0.2.0 
hyperclick 0.0.40 
intentions 1.1.2 
language-babel 2.65.1 
language-elm 1.5.0 
language-fish-shell 1.0.5 
language-ocaml 1.9.3 
language-reason 0.0.3 
linter 2.1.4 
linter-eslint 8.2.1 
linter-flake8 2.2.1 
linter-flow 5.6.0 
linter-stylelint 3.10.0 
linter-ui-default 1.6.0 
minimap 4.28.2 
nuclide 0.230.0 
ocaml-merlin 0.14.4 
project-manager 3.3.5 
react 0.16.2 
reason-refmt 0.1.0 
sort-lines 0.14.0 
tabs-to-spaces 1.0.3 
terminal-plus 0.14.5 
Zen 0.18.0 
```

**Comment by AndrewKvalheim** [comment]
In my case, I'd messed up the [installation of reason-cli][reason-cli] so its `ocamlmerlin` wrapper was returning [an error message][error] instead of typical output. Check `which ocamlmerlin` and `ocamlmerlin -version`.

[reason-cli]: https://facebook.github.io/reason/jsWorkflow.html
[error]: https://github.com/reasonml/reason-cli/blob/beta-v-1.13.5/.bin/ocamlmerlin#L124-L136

**Comment by 314eter** [comment]
Did you solve the problem? If not, which version of merlin do you have installed?

**Comment by eldh** [comment]
I honestly don't remember, but I think @AndrewKvalheim was right in that the `ocamlmerlin` installation was messed up.
