### ISSUE TITLE
ocamlmerlin spawn problem

### ISSUE THREAD

**Issue by acierto** [314eter/atom-ocaml-merlin#39]
When I open new project in atom always see the issue regarding spawning new ocamlmerlin process. And I have it in my classpath.

![screen shot 2017-07-06 at 09 14 35](https://user-images.githubusercontent.com/2265094/27899721-b84db85c-622b-11e7-9357-cc6a865d66e7.png)

Atom version: 1.18.0 x64
Merlin: 2.5.4
OCaml: 4.02.3
OS: Mac 10.11.6

**Comment by 314eter** [comment]
You're using the `linter-ocaml` package instead of `ocaml-merlin`.
