### ISSUE TITLE
installErrorReporter - Caught unhandled rejection ["failure","invalid arguments"]

### ISSUE THREAD

**Issue by acierto** [314eter/atom-ocaml-merlin#40]
1. git clone git@github.com:BuckleScript/bucklescript.git
2. cd bucklescript
3. npm install
4. atom .

Result:
<img width="926" alt="screen shot 2017-07-18 at 14 00 58" src="https://user-images.githubusercontent.com/2265094/28316081-8d635184-6bc1-11e7-99d2-0a4883f02c6a.png">

Atom Version: 1.18.0
OCaml: 4.02.3
Merlin: 2.5.4
atom-ocaml-merlin: 0.14.4

**Comment by 314eter** [comment]
Does it work with the latest version of merlin?
